title: Fishy Tea
description: A site showcasing the development of the Fishy Tea game
google_analytics:
show_downloads: true
theme: jekyll-theme-cayman
github:
  is_project_page: true
  repository_url: https://github.com/mochi-bytes/MochiBytes
gems:
  - jekyll-mentions
